[package]
name = "ndspy-sys"
version = "0.1.1"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"

[features]
download_3delight_lib = ["reqwest"]

[build-dependencies]
bindgen = "^0.54.0"
reqwest = { version = "^0.10.6", features = ["blocking"], optional = true }
